# Generated by Django 6.0.3 on 2026-06-18 10:14

from django.db import migrations


def seed_genres(apps, schema_editor):
    Category = apps.get_model('book', 'Category')
    genres = [
        # Fiction
        'Fiction',
        'Romance',
        'Fantasy',
        'Science Fiction',
        'Mystery',
        'Thriller/Suspense',
        'Horror',
        'Historical Fiction',
        'Young Adult',
        'Dystopian',
        'Contemporary',
        # Non-Fiction
        'Non-Fiction',
        'Biography',
        'Memoir',
        'Self-Help',
        'History',
        'True Crime',
        'Health & Fitness',
        'Cookbooks',
        'Travel',
        'Business & Careers',
        'Science & Nature',
    ]
    for genre in genres:
        Category.objects.get_or_create(name=genre)


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_contactmessage_alter_book_options_book_created_at_and_more'),
    ]

    operations = [
        migrations.RunPython(seed_genres),
    ]
