# Generated by Django 6.0.3 on 2026-06-19 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_seed_genres'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='is_most_read',
            field=models.BooleanField(default=False, help_text='Mark as "Most Read This Week"'),
        ),
        migrations.AddField(
            model_name='book',
            name='is_new_release',
            field=models.BooleanField(default=False, help_text='Mark as "New Release"'),
        ),
    ]
