# Generated by Django 6.0.3 on 2026-06-19 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_book_is_most_read_book_is_new_release'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, help_text='Book description / synopsis'),
        ),
    ]
