# Generated by Django 6.0.3 on 2026-06-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isbn',
            field=models.CharField(blank=True, help_text='ISBN number', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=100),
        ),
        migrations.AddField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, help_text='Number of pages', null=True),
        ),
        migrations.AddField(
            model_name='book',
            name='published',
            field=models.CharField(blank=True, help_text='Year or date published', max_length=50),
        ),
        migrations.AddField(
            model_name='book',
            name='publisher',
            field=models.CharField(blank=True, help_text='Publisher name', max_length=200),
        ),
    ]
